import type { Metadata } from "next";
import Link from "next/link";
import { DocsEligibilityLab, DocsJourney } from "@/components/docs-experience";

export const metadata: Metadata = {
  title: "Docs | Creators, holders & testing",
  description: "How TopBlast launches, verified entry, creator deposits, wallet-approved rewards, and recovery work on StonkFun and Pump.fun.",
};

const sections = [
  ["lab", "Try the Blast Lab"], ["wallet-setup", "Fresh wallet setup"],
  ["start", "Start here"], ["venues", "Launch venues"], ["launch", "Launch & recover"],
  ["funding", "Fund a launch"], ["eligibility", "Holder eligibility"],
  ["proof", "Read the proof"], ["testing", "Testing & activation"],
] as const;

export default function DocsPage() {
  return <main className="page shell docs-page">
    <div className="page-header"><div><div className="eyebrow">THE TOPBLAST FIELD GUIDE</div><h1>YOUR ENTRY.<br /><span>THE RULES.</span></h1></div><p>Bought in. Price dropped. Still holding?<br />Understand what qualifies, who funds the pool, and what a confirmed reward actually means.</p></div>
    <DocsJourney />
    <div className="docs-layout">
      <nav className="docs-index" aria-label="Documentation sections"><span className="section-label">On this page</span>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}<Link href="/launch" className="button button-small">Launch token</Link></nav>
      <article className="docs-body">
        <aside className="docs-callout"><strong>Split 100% of your share.</strong><p>On both StonkFun and Pump.fun, new launches reserve 10% of each declared gross funding amount for the protocol. The two controls total 100% of the remaining 90%. An 80% Rewards / 20% Creator selection therefore allocates 72% of gross funding to rewards, 18% to the creator and 10% to the protocol.</p><p>Controls use 10-point increments so every selection maps exactly to the stored whole-percent policy without hidden rounding. The minimum TopBlast allocation applies to the gross funding amount. The review shows both your share and the complete split, which is fixed at launch. This is a reward-funding allocation, not an additional 10% trading tax or launch charge. Existing launches keep their original rules.</p><p><Link href="/launch">Launch token</Link> checks current venue availability before preparing a transaction. Mainnet costs and wallet approval apply. Launch availability is separate from reward-payout activation.</p></aside>
        <aside className="docs-callout"><strong>StonkFun launch integration updated.</strong><p>New Stonk tokens use its published LaunchLab pricing and standard platform, with its enforced onchain rules. The current standard uses Token-2022 without a transfer tax. Your wallet approves account creation directly, with no initial buy. Stonk’s listing may appear after creation. Trading fees are venue-controlled and shown in the review; TopBlast rewards still need a separate STONK deposit. <a href="https://www.stonkfun.xyz/api/public/v1/openapi.json" target="_blank" rel="noreferrer">Official StonkFun API contract</a>.</p></aside>
        <section id="lab"><div className="eyebrow">TRY IT / NO WALLET NEEDED</div><h2>Would you qualify?<br />Change one thing.</h2><p>Move the price. Sell. Receive tokens. Remove the funding. See which changes affect eligibility and which affect the budget.</p><DocsEligibilityLab /></section>
        <section id="wallet-setup"><div className="eyebrow">QUICK START / YOUR KEYS STAY YOURS</div><h2>Fresh wallet.<br />Public address only.</h2><ol><li>Create a wallet or account in your trusted Solana wallet app and keep its recovery material private.</li><li>Use one account as the creator and a different account as the reward treasury. The protocol treasury may share the reward-treasury address for this MVP.</li><li>Provide only the public treasury addresses for configuration. Never put a private key or recovery phrase into Supabase, Vercel, Railway, this website, or chat.</li><li>After address and infrastructure checks, review a controlled mainnet launch through the platform. Approve its concrete transaction in your creator wallet.</li><li>Then verify funding, buyer tracking, an eligible finalized snapshot, and a treasury-wallet-approved payout. A successful token launch alone does not prove rewards work.</li></ol><aside className="docs-callout"><strong>The platform prepares. Your wallet approves.</strong><p>There is no private-key upload step. Current payouts use manual wallet approval, not unattended server signing. Supabase stores operational records, not treasury keys.</p></aside><p>Keep gas funding separate from reward funding: SOL pays network costs; the launch-specific funding action supplies STONK or WSOL rewards. Review the required amounts before moving funds. <a href="https://solana.com/docs/core/transactions/signing-in-production" target="_blank" rel="noreferrer">Read Solana’s signing guidance</a>.</p></section>
        <section id="start"><div className="eyebrow">01 / THE PRODUCT</div><h2>Launch underneath.<br />Rewards on top.</h2><p>StonkFun or Pump.fun provides token creation and trading infrastructure. TopBlast tracks verified buyers and calculates rewards from that launch’s funded pool. TopBlast does not run its own curve, AMM, or exchange.</p><div className="docs-journeys"><div><h3>For creators</h3><p>Choose a venue and fixed allocation. Review and sign your launch. Fund its rewards from your creator dashboard.</p></div><div><h3>For holders</h3><p>Buy through the recognized market. Keep holding. Look up your wallet on the token page and check confirmed payouts on its proof page.</p></div></div><aside className="docs-callout"><strong>Eligibility is not a guarantee.</strong><p>Rewards depend on verified history, an eligible retained position, a valid snapshot, and available funding. No APY or promise of recovering your losses.</p></aside></section>
        <section id="venues"><div className="eyebrow">02 / CHOOSE YOUR VENUE</div><h2>Two options.<br />One reward engine.</h2><div className="docs-table" role="region" aria-label="Venue comparison" tabIndex={0}><table className="proof-table"><thead><tr><th scope="col">Venue</th><th scope="col">Pair</th><th scope="col">Reward asset</th><th scope="col">Funding</th></tr></thead><tbody><tr><th scope="row">StonkFun</th><td>STONK</td><td>STONK</td><td>Explicit creator deposit</td></tr><tr><th scope="row">Pump.fun</th><td>SOL</td><td>Wrapped SOL (WSOL)</td><td>Explicit creator deposit</td></tr></tbody></table></div><p>Pump support uses the official creation instruction, with no initial buy. Native Pump holder rewards, cashback, mayhem mode, and non-SOL pairs are not enabled.</p><aside className="docs-callout"><strong>Pump support is for controlled testing.</strong><p>PumpSwap graduation is not supported. Tracking and new reward epochs pause when a Pump curve graduates. Do not assume uninterrupted rewards after graduation.</p></aside><p>Venue activation depends on the checks displayed in the <Link href="/launch">launch form</Link>. A supported option is not evidence of a completed real launch-to-payout test.</p></section>
        <section id="launch"><div className="eyebrow">03 / CREATOR FLOW</div><h2>Review. Sign.<br />Keep the receipt.</h2><ol><li>Connect your creator wallet on Solana mainnet. Choose the venue, token details, image, and fee allocation. Allocations total 100% and are fixed at launch.</li><li>Review the token, pair, allocation, network, fee payer, recipient or program, and payment estimate. Expired quotes need a fresh review. Switching wallet accounts invalidates the prepared quote.</li><li>Approve in your wallet only after reviewing the transaction. Creation costs real funds. Pump creation estimates can change with network fees.</li><li>Keep the receipt. A timeout does not mean the transaction failed. Use the existing recovery action or creator dashboard before starting another launch.</li><li>Wait for token creation and tracker activation separately. If the token exists but tracking is pending, retry registration without paying for another token.</li></ol><p>Submission receipts are stored before broadcast, and the browser retains its recovery reference. Use the same wallet after refresh. Never send a second payment just because a response is slow.</p></section>
        <section id="funding"><div className="eyebrow">04 / REAL FUNDING ONLY</div><h2>No deposit.<br />No reward budget.</h2><p>Automatic creator-fee routing is not active. Claim any venue fees through the venue’s supported flow, then use <strong>Fund rewards</strong> in the <Link href="/creator">creator dashboard</Link>. An allocation slider does not redirect venue fees onchain.</p><p>Enter a gross amount for the configured split. The reward and protocol portions are transferred; the creator portion stays in the creator wallet. For example only, a 70/20/10 split on 100 units sends 70 to rewards and 10 to the protocol, retaining 20. It does not deposit 100 into the reward pool.</p><p>For StonkFun, funding transfers STONK. For Pump, the transferred portions are wrapped from SOL into WSOL. Wrapping is not a swap. You also need SOL for network fees and account rent.</p><p>The creator wallet must differ from the reward treasury. Use the funding action rather than an arbitrary transfer: the signed transaction binds the launch, sender, recipients, mint, exact amounts, and unique funding reference. Credit requires finalized verification. A deposit cannot be credited twice or used by another launch.</p><aside className="docs-callout"><strong>Funding is isolated per launch.</strong><p>Token A’s attributable budget cannot fund Token B’s holders, even when the same wallet holds both tokens.</p></aside></section>
        <section id="eligibility"><div className="eyebrow">05 / THE BLAST ZONE</div><h2>Verified buys<br />set your entry.</h2><ul><li>Only recognized, successful market buys create purchased cost basis. Multiple buys produce a quantity-weighted average entry.</li><li>Incoming transfers create no purchased cost basis. They do not turn transferred tokens into verified eligible units.</li><li>A sell or outgoing transfer excludes the wallet for that epoch. Outgoing activity consumes verified units first.</li><li>Uncertain or incomplete history, stale prices, and unverified activity cannot produce payable allocations.</li><li>Eligibility is evaluated against a consistent finalized snapshot, not the moving price in an illustrative chart.</li></ul><div className="docs-formula"><span className="section-label">Loss weighting</span><p>Eligible loss = retained verified units × max(average entry − snapshot price, 0)</p><p>Wallet allocation = funded epoch budget × wallet eligible loss ÷ total eligible loss</p></div><p>The engine uses exact integer amounts, configured caps, and deterministic rounding. Total allocations cannot exceed the reserved funded budget. Previous rewards remain in history; they are not silently substituted for a different eligibility formula.</p><p>Wallet lookup distinguishes eligible, above entry, transferred, sold this epoch, insufficient history, and not a verified buyer. The interactive homepage graphic and free test use examples, not live account balances.</p></section>
        <section id="proof"><div className="eyebrow">06 / FOLLOW THE MONEY</div><h2>Allocated<br />does not mean paid.</h2><dl className="docs-definitions"><div><dt>Available</dt><dd>Finalized, attributable funding not reserved for an epoch.</dd></div><div><dt>Reserved</dt><dd>Budget held for a specific epoch. It cannot fund another epoch at the same time.</dd></div><div><dt>Allocated</dt><dd>A calculated share for a wallet. No transfer is implied.</dd></div><div><dt>Submitted</dt><dd>A signed payout has been broadcast. Finalized payment has not yet been verified.</dd></div><div><dt>Paid</dt><dd>The transfer has been verified onchain. Public totals count confirmed payouts, not proposed allocations.</dd></div></dl><p>Each token’s proof page records snapshot slot and time, funding receipts, budget, wallet allocations, payout states, and transaction links. Pending or failed batches retain their state for reconciliation. Restarting the worker must not create another payment for an already-paid allocation.</p><p>Current payout mode requires a treasury wallet approval in Admin. The server prepares concrete transaction details; it does not need a treasury private key in its environment.</p></section>
        <section id="testing"><div className="eyebrow">07 / BEFORE REAL MONEY</div><h2>Rehearse first.<br />Then prove the cycle.</h2><p><Link href="/test">Test now</Link> runs a free browser simulation using the position and allocation logic. Try both venues, sells, transfers, zero funding, and partial-payout recovery. It creates no token and sends no funds. <strong>It is not devnet or proof of live payouts.</strong></p><p>A real controlled acceptance test must demonstrate: launch → verified buy → attributable funding → finalized eligibility → funded allocation → confirmed payout → public proof → restart without duplication. A price drop and actual eligible loss are required; do not manipulate a market to manufacture eligibility.</p><p>Operators must configure public reward and protocol treasury addresses, verify database and worker health, and explicitly enable controlled launches. No seed phrase or private key should be pasted into chat, Vercel, or Railway for manual-wallet mode.</p><aside className="docs-callout"><strong>DRY_RUN is not a free-launch switch.</strong><p>With launches enabled, creation is a real mainnet transaction even when DRY_RUN is true. Dry run locks funding and payout submission. Turning it off and enabling epoch planning should follow review of the controlled real-funds test.</p></aside><div className="hero-actions"><Link href="/test" className="button">Run free simulation</Link><Link href="/launch" className="button button-secondary">Check launch availability</Link></div></section>
      </article>
    </div>
  </main>;
}
