import type { Metadata } from "next";
import Link from "next/link";
import { DocsEligibilityLab, DocsJourney } from "@/components/docs-experience";

export const metadata: Metadata = {
  title: "Docs | Creators, holders & testing",
  description: "How TopBlast launches, verifies entry, attributes creator fees, airdrops rewards, and recovers safely on StonkFun and Pump.fun.",
};

const sections = [
  ["quick-start", "Five-minute quick start"],
  ["lab", "Try the Blast Lab"], ["wallet-setup", "Fresh wallet setup"],
  ["start", "Start here"], ["venues", "Launch venues"], ["launch", "Launch & recover"],
  ["funding", "Fund a launch"], ["eligibility", "Holder eligibility"],
  ["proof", "Read the proof"], ["testing", "Testing & activation"],
  ["not", "What TopBlast is not"], ["weighted-entry", "Weighted entry calculation"],
  ["epochs", "Epoch lifecycle"], ["allocation", "Deposit allocation"], ["payout-approval", "Payout approval"],
  ["recovery", "Recovery"], ["limitations", "Known limitations"], ["security", "Security"], ["risks", "Risk disclosures"],
] as const;

export default function DocsPage() {
  return <main className="page shell docs-page">
    <div className="page-header"><div><div className="eyebrow">THE TOPBLAST FIELD GUIDE</div><h1>YOUR ENTRY.<br /><span>THE RULES.</span></h1></div><p>Bought in. Price dropped. Still holding?<br />Understand what qualifies, who funds the pool, and what a confirmed reward actually means.</p></div>
    <DocsJourney />
    <div className="docs-layout">
      <nav className="docs-index" aria-label="Documentation sections"><span className="section-label">On this page</span>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}<Link href="/launch" className="button button-small">Launch token</Link></nav>
      <article className="docs-body">
        <section id="quick-start"><div className="eyebrow">FIVE-MINUTE QUICK START</div><h2>Know the loop.<br />Then sign.</h2><ol><li>Choose StonkFun or Pump.fun. All token launches use Solana mainnet and require wallet approval.</li><li>Choose a currently launchable Stonk pair or a pair on Pump.fun’s current official allowlist. Pump remains beta.</li><li>Use a creator wallet separate from the configured reward treasury. Review token details, the fixed allocation, network, fee recipient and transaction cost before signing.</li><li>Keep the launch receipt. A successful token launch and successful tracker activation are separate states.</li><li>For Stonk, verified creator-fee forwards automatically credit only the matching launch. Optional creator top-ups use the same fixed allocation.</li><li>Wait for complete history and a finalized eligible snapshot. The Railway-only treasury signer sends direct airdrops within its configured ceiling. Only finalized recipient transactions count as paid.</li></ol><p><strong>Automatic does not mean unverified. No matching finalized fee receipt, no reward budget.</strong></p></section>
        <aside className="docs-callout"><strong>One simple creator choice.</strong><p>Choose the percentage of distributable fees sent to Holder rewards; Creator receives the remainder. The two visible values always total 100%. TopBlast applies its fixed 10% protocol share automatically underneath for designated buybacks and burns.</p><p>Controls use 10-point increments so every selection maps exactly to the stored policy without hidden rounding. The review shows the selected split and its enforced funding amounts before approval. This is a funding allocation, not an additional trading tax or launch charge. Existing launches keep their original rules.</p><p><Link href="/launch">Launch token</Link> checks current venue availability before preparing a transaction. Mainnet costs and wallet approval apply. Launch availability is separate from reward-payout activation.</p></aside>
        <aside className="docs-callout"><strong>StonkFun fee-forward verification.</strong><p>New Stonk tokens use its published LaunchLab pricing and standard platform, with its enforced onchain rules. The current standard uses Token-2022 without a transfer tax. Your wallet approves account creation directly, with no initial buy. Stonk states that it automatically forwards a share of platform fees to the creator wallet. TopBlast must verify both receipt and token attribution before crediting rewards. That forwarded-fee path has not yet passed our production acceptance test. More trading volume alone does not establish that it works. Optional deposits are a separate funding path, not proof of automatic fee collection. <a href="https://www.stonkfun.xyz/api/public/v1/openapi.json" target="_blank" rel="noreferrer">Official StonkFun API contract</a>.</p></aside>
        <section id="lab"><div className="eyebrow">TRY IT / NO WALLET NEEDED</div><h2>Would you qualify?<br />Change one thing.</h2><p>Move the price. Sell. Receive tokens. Remove the funding. See which changes affect eligibility and which affect the budget.</p><DocsEligibilityLab /></section>
        <section id="wallet-setup"><div className="eyebrow">QUICK START / YOUR KEYS STAY YOURS</div><h2>Fresh wallet.<br />Public address only.</h2><ol><li>Create a wallet or account in your trusted Solana wallet app and keep its recovery material private.</li><li>Use one account as the creator and a different account as the reward treasury. The protocol treasury may share the reward-treasury address for this MVP.</li><li>Provide only public treasury addresses in the website. Never put a private key or recovery phrase into Supabase, Vercel, browser storage, this website, Git, or chat.</li><li>After address and infrastructure checks, review a mainnet launch through the platform. Approve its concrete transaction in your creator wallet.</li><li>Then verify funding, buyer tracking, an eligible finalized snapshot, and a confirmed direct holder payout. A successful token launch alone does not prove rewards work.</li></ol><aside className="docs-callout"><strong>Holders never claim.</strong><p>TopBlast sends direct airdrops after finalized eligibility. Operations can use browser-wallet approval or an isolated Railway-only signer. A server signer must match the public treasury, sign only exact stored messages, and enforce a payout ceiling. Supabase never stores its key.</p></aside><p>Keep gas funding separate from reward funding: SOL pays network costs; the launch-specific funding action supplies its selected quote asset. SOL-paired Pump funding wraps SOL into WSOL without a swap. Review the required amounts before moving funds. <a href="https://solana.com/docs/core/transactions/signing-in-production" target="_blank" rel="noreferrer">Read Solana’s signing guidance</a>.</p></section>
        <section id="start"><div className="eyebrow">01 / THE PRODUCT</div><h2>Launch underneath.<br />Rewards on top.</h2><p>StonkFun or Pump.fun provides token creation and trading infrastructure. TopBlast tracks verified buyers and calculates rewards from that launch’s funded pool. TopBlast does not run its own curve, AMM, or exchange.</p><div className="docs-journeys"><div><h3>For creators</h3><p>Choose a venue and fixed allocation. Review and sign your launch. Fund its rewards from your creator dashboard.</p></div><div><h3>For holders</h3><p>Buy through the recognized market. Keep holding. Look up your wallet on the token page and check confirmed payouts on its proof page.</p></div></div><aside className="docs-callout"><strong>Eligibility is not a guarantee.</strong><p>Rewards depend on verified history, an eligible retained position, a valid snapshot, and available funding. No APY or promise of recovering your losses.</p></aside></section>
        <section id="venues"><div className="eyebrow">02 / CHOOSE YOUR VENUE</div><h2>Two options.<br />One reward engine.</h2><div className="docs-table" role="region" aria-label="Venue comparison" tabIndex={0}><table className="proof-table"><thead><tr><th scope="col">Venue</th><th scope="col">Pair</th><th scope="col">Reward asset</th><th scope="col">Funding</th></tr></thead><tbody><tr><th scope="row">StonkFun</th><td>Any live LaunchLab pair</td><td>Selected quote asset</td><td>Verified creator-fee forward</td></tr><tr><th scope="row">Pump.fun</th><td>Official supported-pair allowlist</td><td>Selected quote asset</td><td>Explicit creator deposit</td></tr></tbody></table></div><p>Pump support uses the official creation instruction and current supported-pair allowlist, with no initial buy. Native Pump holder rewards, cashback, and mayhem mode are not enabled. Arbitrary unapproved quote mints are rejected.</p><aside className="docs-callout"><strong>Pump support remains beta.</strong><p>PumpSwap graduation is not supported. Tracking and new reward epochs pause when a Pump curve graduates. Do not assume uninterrupted rewards after graduation.</p></aside><p>Venue activation depends on the checks displayed in the <Link href="/launch">launch form</Link>. A supported option is not evidence of a completed real launch-to-payout test.</p></section>
        <section id="launch"><div className="eyebrow">03 / CREATOR FLOW</div><h2>Review. Sign.<br />Keep the receipt.</h2><ol><li>Connect your creator wallet on Solana mainnet. Choose the venue, token details, image, and fee allocation. Allocations total 100% and are fixed at launch.</li><li>Review the token, pair, allocation, network, fee payer, recipient or program, and payment estimate. Expired quotes need a fresh review. Switching wallet accounts invalidates the prepared quote.</li><li>Approve in your wallet only after reviewing the transaction. Creation costs real funds. Pump creation estimates can change with network fees.</li><li>Keep the receipt. A timeout does not mean the transaction failed. Use the existing recovery action or creator dashboard before starting another launch.</li><li>Wait for token creation and tracker activation separately. If the token exists but tracking is pending, retry registration without paying for another token.</li></ol><p>Submission receipts are stored before broadcast, and the browser retains its recovery reference. Use the same wallet after refresh. Never send a second payment just because a response is slow.</p></section>
        <section id="funding"><div className="eyebrow">04 / VERIFIED FEE FUNDING</div><h2>Exact receipt.<br />Exact launch.</h2><p>New Stonk launches set the TopBlast treasury as the onchain creator-fee recipient while the connected creator remains the launch payer and product owner. LaunchLab forwards creator fees in the chosen quote asset.</p><p>For Pump, the worker creates and permanently locks Pump.fun’s official fee-sharing config for that mint. This replaces creator-wide attribution with a per-mint vault and finalized distribution event.</p><p>The worker accepts a fee only when the finalized transaction matches that launch’s exact venue route, quote mint, TopBlast destination, slot range and measured balance delta. The signature is globally single-use, so the same receipt cannot fund two launches.</p><p>The immutable allocation then credits the holder budget, records protocol revenue, and prepares the creator share for an automatic transfer back to the creator wallet. Optional top-ups remain available and use the same allocation.</p><aside className="docs-callout"><strong>Funding is isolated per launch.</strong><p>Token A’s attributable budget cannot fund Token B’s holders, even when the same wallet holds both tokens.</p></aside></section>
        <section id="eligibility"><div className="eyebrow">05 / THE BLAST ZONE</div><h2>Verified buys<br />set your entry.</h2><ul><li>Only recognized, successful market buys create purchased cost basis. Multiple buys produce a quantity-weighted average entry.</li><li>Incoming transfers create no purchased cost basis. They do not turn transferred tokens into verified eligible units.</li><li>A sell or outgoing transfer excludes the wallet for that epoch. Outgoing activity consumes verified units first.</li><li>Uncertain or incomplete history, stale prices, and unverified activity cannot produce payable allocations.</li><li>Eligibility is evaluated against a consistent finalized snapshot, not the moving price in an illustrative chart.</li></ul><div className="docs-formula"><span className="section-label">Loss weighting</span><p>Eligible loss = retained verified units × max(average entry − snapshot price, 0)</p><p>Wallet allocation = funded epoch budget × wallet eligible loss ÷ total eligible loss</p></div><p>The engine uses exact integer amounts, configured caps, and deterministic rounding. Total allocations cannot exceed the reserved funded budget. Previous rewards remain in history; they are not silently substituted for a different eligibility formula.</p><p>Wallet lookup distinguishes eligible, above entry, transferred, sold this epoch, insufficient history, and not a verified buyer. The interactive homepage graphic and free test use examples, not live account balances.</p></section>
        <section id="proof"><div className="eyebrow">06 / FOLLOW THE MONEY</div><h2>Allocated<br />does not mean paid.</h2><dl className="docs-definitions"><div><dt>Available</dt><dd>Finalized, attributable funding not reserved for an epoch.</dd></div><div><dt>Reserved</dt><dd>Budget held for a specific epoch. It cannot fund another epoch at the same time.</dd></div><div><dt>Allocated</dt><dd>A calculated share for a wallet. No transfer is implied.</dd></div><div><dt>Submitted</dt><dd>A signed payout has been broadcast. Finalized payment has not yet been verified.</dd></div><div><dt>Paid</dt><dd>The transfer has been verified onchain. Public totals count confirmed payouts, not proposed allocations.</dd></div></dl><p>Each token’s proof page records snapshot slot and time, funding receipts, budget, wallet allocations, payout states, and transaction links. Pending or failed batches retain their state for reconciliation. Restarting the worker must not create another payment for an already-paid allocation.</p><p>The isolated Railway signer binds each exact creator distribution and holder-airdrop transaction before broadcast, enforces a batch ceiling, and counts only finalized proof as paid.</p></section>
        <section id="testing"><div className="eyebrow">07 / ACTIVATION & VERIFICATION</div><h2>Real receipts.<br />A proven cycle.</h2><p>Illustrative examples explain the rules. They create no token and send no funds. <strong>They are not proof of live payouts.</strong></p><p>A real controlled acceptance test must demonstrate: launch → verified buy → attributable funding → finalized eligibility → funded allocation → confirmed payout → public proof → restart without duplication. A price drop and actual eligible loss are required; do not manipulate a market to manufacture eligibility.</p><p>Operators must configure public reward and protocol treasury addresses, verify database and worker health, and explicitly enable controlled launches. No seed phrase or private key should be pasted into chat, Vercel, or Railway for manual-wallet mode.</p><aside className="docs-callout"><strong>DRY_RUN is not a free-launch switch.</strong><p>With launches enabled, creation is a real mainnet transaction even when DRY_RUN is true. Dry run locks funding and payout submission. Turning it off and enabling epoch planning should follow review of the controlled real-funds test.</p></aside><div className="hero-actions"><Link href="/launch" className="button">Launch token</Link><Link href="/explore" className="button button-secondary">Explore launches</Link></div></section>
        <section id="not"><h2>What this is not.</h2><p>TopBlast is not an exchange, bonding curve, AMM, insurance policy, or guaranteed loss-recovery product. Venue names identify integrations, not endorsement or operation by those venues.</p></section>
        <section id="weighted-entry"><h2>Your weighted entry.</h2><p>Only verified market buys establish cost. Buy 10 units for 20 quote units, then 10 for 40: the retained 20-unit position has an average entry of 3 quote units. Received tokens establish no new purchased basis. Outgoing activity consumes verified units first and excludes the wallet for the applicable epoch.</p><p>Calculations use actual mint decimals and integer base units. UI spot prices are not authorization for a payout; the finalized snapshot uses its validated price source.</p></section>
        <section id="epochs"><h2>One finalized checkpoint.</h2><p>Schedule → acquire worker lease → reconcile finalized history → validate snapshot price → reserve attributable funding → record wallet snapshots → calculate loss-weighted allocations → prepare batches → obtain treasury approval → submit → reconcile finality → publish proof.</p><p>Each eligible epoch atomically reserves 65% of that launch’s currently available holder-reward balance. The other 35% remains available only to that launch and carries forward to later epochs. Integer rounding always rounds the reservation down, so the engine cannot exceed funded atoms.</p><p>Missing history, stale price, unsupported markets and engine pauses stop payable allocation. A zero-funded epoch cannot distribute rewards.</p></section>
        <section id="allocation"><h2>Fixed at launch.</h2><p>The creator selects a simple Holder rewards / Creator split that totals 100%. TopBlast then enforces its fixed 10% protocol share automatically on each verified receipt and optional top-up. The review shows the selected split and exact resulting funding amounts before approval.</p><p>The 10% protocol allocation is designated for TOPBLAST market buybacks and burns. Allocation to the protocol treasury is not itself a buyback or burn. Completed purchases and burn transfers must be confirmed onchain and published before the product reports them as executed or burned.</p></section>
        <section id="payout-approval"><h2>Your treasury pays holders.</h2><p>TopBlast prepares launch-scoped direct-airdrop batches containing the exact asset, recipients, amounts, fee payer and network. Manual mode uses treasury-wallet approval. Server mode uses a Railway-only key that must match the configured treasury, signs only the stored message, enforces a per-batch ceiling and serializes unresolved spending.</p><p>Holders never claim. Never approve an unexplained transfer. Reserved and submitted balances are not confirmed payouts.</p></section>
        <section id="recovery"><h2>Recover the receipt.<br />Do not pay twice.</h2><p>After a timeout, refresh or closed tab, use the saved launch or funding receipt. A delayed response does not establish failure. The server binds signed transactions before broadcasting and reconciles their finality. A restart must resume the same payment, not generate a replacement.</p><p>Partial payout recovery operates per batch and recipient. Confirmed transfers stay paid; unresolved batches remain reserved or submitted until reconciled. Retry tracking after a completed launch without creating another token.</p></section>
        <section id="limitations"><h2>Know the boundaries.</h2><ul><li>Automatic creator-fee funding uses verified Stonk LaunchLab forwards or Pump.fun’s official per-mint fee-sharing config.</li><li>Pump remains beta: official supported pairs only, no initial buy, native cashback, or mayhem.</li><li>PumpSwap graduation is unsupported. Tracking and new reward epochs pause after unsupported graduation.</li><li>The complete Pump production cycle must still be demonstrated with a real finalized launch, fee distribution and payout before it is marked generally available.</li><li>Controlled tests are real mainnet tokens. Hiding a listing cannot remove onchain history.</li></ul></section>
        <section id="security"><h2>Exact transactions only.</h2><p>Never paste private keys or recovery phrases into this site, chat, browser storage, Supabase, Vercel or Git. Connect only through a trusted wallet and review each exact transaction. If automatic payouts are selected, the treasury key is entered directly into Railway’s protected worker variables and nowhere else.</p><p>Financial records are scoped to launch IDs. Funding signatures cannot be reused across launches; database reservations prevent competing epochs from spending the same budget. Public readers cannot modify financial records. Operator actions require separate authorization; connecting a wallet to view public data does not grant administrative access.</p><p>Report unexpected recipients, missing receipts or inconsistent balances before signing anything else. Large treasury movements should use an independently reviewed approval process.</p></section>
        <section id="risks"><h2>Participation.<br />Not protection.</h2><p>TopBlast rewards participation. It does not promise to recover losses. Token prices can fall to zero. Eligibility and funding may be insufficient, delayed or unavailable. Venue, RPC, wallet and smart-contract failures can interrupt operation. No APY, guaranteed payment or guaranteed principal recovery is offered.</p></section>
      </article>
    </div>
  </main>;
}
