import type { Metadata } from "next";
import Link from "next/link";
import { DocsEligibilityLab, DocsJourney } from "@/components/docs-experience";

export const metadata: Metadata = {
  title: "Docs | Creators, holders & testing",
  description: "How TopBlast launches, verified entry, creator deposits, wallet-approved rewards, and recovery work on StonkFun and Pump.fun.",
};

const sections = [
  ["quick-start", "Five-minute quick start"],
  ["lab", "Try the Blast Lab"], ["wallet-setup", "Fresh wallet setup"],
  ["start", "Start here"], ["venues", "Launch venues"], ["launch", "Launch & recover"],
  ["funding", "Fund a launch"], ["eligibility", "Holder eligibility"],
  ["proof", "Read the proof"], ["testing", "Testing & activation"],
  ["not", "What TopBlast is not"], ["weighted-entry", "Weighted entry calculation"],
  ["epochs", "Epoch lifecycle"], ["allocation", "Deposit allocation"], ["payout-approval", "Payout approval"],
  ["recovery", "Recovery"], ["limitations", "Known limitations"], ["security", "Security"], ["risks", "Risk disclosures"],
] as const;

export default function DocsPage() {
  return <main className="page shell docs-page">
    <div className="page-header"><div><div className="eyebrow">THE TOPBLAST FIELD GUIDE</div><h1>YOUR ENTRY.<br /><span>THE RULES.</span></h1></div><p>Bought in. Price dropped. Still holding?<br />Understand what qualifies, who funds the pool, and what a confirmed reward actually means.</p></div>
    <DocsJourney />
    <div className="docs-layout">
      <nav className="docs-index" aria-label="Documentation sections"><span className="section-label">On this page</span>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}<Link href="/launch" className="button button-small">Launch token</Link></nav>
      <article className="docs-body">
        <section id="quick-start"><div className="eyebrow">FIVE-MINUTE QUICK START</div><h2>Know the loop.<br />Then sign.</h2><ol><li>Choose StonkFun or Pump.fun. All token launches use Solana mainnet and require wallet approval.</li><li>Check each venue’s current status. Public launching stays closed until the complete real reward cycle is accepted. Pump remains beta.</li><li>Use a creator wallet separate from the configured reward treasury. Review token details, the fixed allocation, network, program, treasuries and transaction cost before signing.</li><li>Keep the launch receipt. A successful token launch and successful tracker activation are separate states.</li><li>When live funding is enabled, open your creator dashboard and review an explicit deposit. Verify its finalized funding receipt.</li><li>Wait for complete history and a finalized eligible snapshot. The treasury wallet must approve a prepared payout. Only finalized recipient transactions count as paid.</li></ol><p><strong>Venue fees do not automatically become rewards. Creators explicitly fund each launch’s isolated reward pool.</strong></p></section>
        <aside className="docs-callout"><strong>Split 100% of your share.</strong><p>On both StonkFun and Pump.fun, new launches reserve 10% of each declared gross funding amount for the protocol. The two controls total 100% of the remaining 90%. An 80% Rewards / 20% Creator selection therefore allocates 72% of gross funding to rewards, 18% to the creator and 10% to the protocol.</p><p>Controls use 10-point increments so every selection maps exactly to the stored whole-percent policy without hidden rounding. The minimum TopBlast allocation applies to the gross funding amount. The review shows both your share and the complete split, which is fixed at launch. This is a reward-funding allocation, not an additional 10% trading tax or launch charge. Existing launches keep their original rules.</p><p><Link href="/launch">Launch token</Link> checks current venue availability before preparing a transaction. Mainnet costs and wallet approval apply. Launch availability is separate from reward-payout activation.</p></aside>
        <aside className="docs-callout"><strong>StonkFun launch integration updated.</strong><p>New Stonk tokens use its published LaunchLab pricing and standard platform, with its enforced onchain rules. The current standard uses Token-2022 without a transfer tax. Your wallet approves account creation directly, with no initial buy. Stonk’s listing may appear after creation. Trading fees are venue-controlled and shown in the review; TopBlast rewards still need a separate STONK deposit. <a href="https://www.stonkfun.xyz/api/public/v1/openapi.json" target="_blank" rel="noreferrer">Official StonkFun API contract</a>.</p></aside>
        <section id="lab"><div className="eyebrow">TRY IT / NO WALLET NEEDED</div><h2>Would you qualify?<br />Change one thing.</h2><p>Move the price. Sell. Receive tokens. Remove the funding. See which changes affect eligibility and which affect the budget.</p><DocsEligibilityLab /></section>
        <section id="wallet-setup"><div className="eyebrow">QUICK START / YOUR KEYS STAY YOURS</div><h2>Fresh wallet.<br />Public address only.</h2><ol><li>Create a wallet or account in your trusted Solana wallet app and keep its recovery material private.</li><li>Use one account as the creator and a different account as the reward treasury. The protocol treasury may share the reward-treasury address for this MVP.</li><li>Provide only public treasury addresses in the website. Never put a private key or recovery phrase into Supabase, Vercel, browser storage, this website, Git, or chat.</li><li>After address and infrastructure checks, review a mainnet launch through the platform. Approve its concrete transaction in your creator wallet.</li><li>Then verify funding, buyer tracking, an eligible finalized snapshot, and a confirmed direct holder payout. A successful token launch alone does not prove rewards work.</li></ol><aside className="docs-callout"><strong>Holders never claim.</strong><p>TopBlast sends direct airdrops after finalized eligibility. Operations can use browser-wallet approval or an isolated Railway-only signer. A server signer must match the public treasury, sign only exact stored messages, and enforce a payout ceiling. Supabase never stores its key.</p></aside><p>Keep gas funding separate from reward funding: SOL pays network costs; the launch-specific funding action supplies STONK or WSOL rewards. Review the required amounts before moving funds. <a href="https://solana.com/docs/core/transactions/signing-in-production" target="_blank" rel="noreferrer">Read Solana’s signing guidance</a>.</p></section>
        <section id="start"><div className="eyebrow">01 / THE PRODUCT</div><h2>Launch underneath.<br />Rewards on top.</h2><p>StonkFun or Pump.fun provides token creation and trading infrastructure. TopBlast tracks verified buyers and calculates rewards from that launch’s funded pool. TopBlast does not run its own curve, AMM, or exchange.</p><div className="docs-journeys"><div><h3>For creators</h3><p>Choose a venue and fixed allocation. Review and sign your launch. Fund its rewards from your creator dashboard.</p></div><div><h3>For holders</h3><p>Buy through the recognized market. Keep holding. Look up your wallet on the token page and check confirmed payouts on its proof page.</p></div></div><aside className="docs-callout"><strong>Eligibility is not a guarantee.</strong><p>Rewards depend on verified history, an eligible retained position, a valid snapshot, and available funding. No APY or promise of recovering your losses.</p></aside></section>
        <section id="venues"><div className="eyebrow">02 / CHOOSE YOUR VENUE</div><h2>Two options.<br />One reward engine.</h2><div className="docs-table" role="region" aria-label="Venue comparison" tabIndex={0}><table className="proof-table"><thead><tr><th scope="col">Venue</th><th scope="col">Pair</th><th scope="col">Reward asset</th><th scope="col">Funding</th></tr></thead><tbody><tr><th scope="row">StonkFun</th><td>STONK</td><td>STONK</td><td>Explicit creator deposit</td></tr><tr><th scope="row">Pump.fun</th><td>SOL</td><td>Wrapped SOL (WSOL)</td><td>Explicit creator deposit</td></tr></tbody></table></div><p>Pump support uses the official creation instruction, with no initial buy. Native Pump holder rewards, cashback, mayhem mode, and non-SOL pairs are not enabled.</p><aside className="docs-callout"><strong>Pump support remains beta.</strong><p>PumpSwap graduation is not supported. Tracking and new reward epochs pause when a Pump curve graduates. Do not assume uninterrupted rewards after graduation.</p></aside><p>Venue activation depends on the checks displayed in the <Link href="/launch">launch form</Link>. A supported option is not evidence of a completed real launch-to-payout test.</p></section>
        <section id="launch"><div className="eyebrow">03 / CREATOR FLOW</div><h2>Review. Sign.<br />Keep the receipt.</h2><ol><li>Connect your creator wallet on Solana mainnet. Choose the venue, token details, image, and fee allocation. Allocations total 100% and are fixed at launch.</li><li>Review the token, pair, allocation, network, fee payer, recipient or program, and payment estimate. Expired quotes need a fresh review. Switching wallet accounts invalidates the prepared quote.</li><li>Approve in your wallet only after reviewing the transaction. Creation costs real funds. Pump creation estimates can change with network fees.</li><li>Keep the receipt. A timeout does not mean the transaction failed. Use the existing recovery action or creator dashboard before starting another launch.</li><li>Wait for token creation and tracker activation separately. If the token exists but tracking is pending, retry registration without paying for another token.</li></ol><p>Submission receipts are stored before broadcast, and the browser retains its recovery reference. Use the same wallet after refresh. Never send a second payment just because a response is slow.</p></section>
        <section id="funding"><div className="eyebrow">04 / REAL FUNDING ONLY</div><h2>No deposit.<br />No reward budget.</h2><p>Venue fees do not automatically become rewards. Creators explicitly fund each launch’s isolated reward pool.</p><p>Claim any venue fees through the venue’s supported flow, then use <strong>Fund rewards</strong> in the <Link href="/creator">creator dashboard</Link>. An allocation slider does not redirect venue fees onchain.</p><p>Enter a gross amount for the configured split. The reward and protocol portions are transferred; the creator portion stays in the creator wallet. An 80/20 selection on the creator’s 90% share means 72/18/10 of gross: declaring 100 units sends 72 to rewards and 10 to the protocol, retaining 18. It does not deposit 100 into the reward pool.</p><p>For StonkFun, funding transfers STONK. For Pump, the transferred portions are wrapped from SOL into WSOL. Wrapping is not a swap. You also need SOL for network fees and account rent.</p><p>The creator wallet must differ from the reward treasury. Use the funding action rather than an arbitrary transfer: the signed transaction binds the launch, sender, recipients, mint, exact amounts, and unique funding reference. Credit requires finalized verification. A deposit cannot be credited twice or used by another launch.</p><aside className="docs-callout"><strong>Funding is isolated per launch.</strong><p>Token A’s attributable budget cannot fund Token B’s holders, even when the same wallet holds both tokens.</p></aside></section>
        <section id="eligibility"><div className="eyebrow">05 / THE BLAST ZONE</div><h2>Verified buys<br />set your entry.</h2><ul><li>Only recognized, successful market buys create purchased cost basis. Multiple buys produce a quantity-weighted average entry.</li><li>Incoming transfers create no purchased cost basis. They do not turn transferred tokens into verified eligible units.</li><li>A sell or outgoing transfer excludes the wallet for that epoch. Outgoing activity consumes verified units first.</li><li>Uncertain or incomplete history, stale prices, and unverified activity cannot produce payable allocations.</li><li>Eligibility is evaluated against a consistent finalized snapshot, not the moving price in an illustrative chart.</li></ul><div className="docs-formula"><span className="section-label">Loss weighting</span><p>Eligible loss = retained verified units × max(average entry − snapshot price, 0)</p><p>Wallet allocation = funded epoch budget × wallet eligible loss ÷ total eligible loss</p></div><p>The engine uses exact integer amounts, configured caps, and deterministic rounding. Total allocations cannot exceed the reserved funded budget. Previous rewards remain in history; they are not silently substituted for a different eligibility formula.</p><p>Wallet lookup distinguishes eligible, above entry, transferred, sold this epoch, insufficient history, and not a verified buyer. The interactive homepage graphic and free test use examples, not live account balances.</p></section>
        <section id="proof"><div className="eyebrow">06 / FOLLOW THE MONEY</div><h2>Allocated<br />does not mean paid.</h2><dl className="docs-definitions"><div><dt>Available</dt><dd>Finalized, attributable funding not reserved for an epoch.</dd></div><div><dt>Reserved</dt><dd>Budget held for a specific epoch. It cannot fund another epoch at the same time.</dd></div><div><dt>Allocated</dt><dd>A calculated share for a wallet. No transfer is implied.</dd></div><div><dt>Submitted</dt><dd>A signed payout has been broadcast. Finalized payment has not yet been verified.</dd></div><div><dt>Paid</dt><dd>The transfer has been verified onchain. Public totals count confirmed payouts, not proposed allocations.</dd></div></dl><p>Each token’s proof page records snapshot slot and time, funding receipts, budget, wallet allocations, payout states, and transaction links. Pending or failed batches retain their state for reconciliation. Restarting the worker must not create another payment for an already-paid allocation.</p><p>Direct holder payouts can use manual treasury approval or the isolated Railway signer. Both modes bind the exact transaction before broadcast and count only finalized proof as paid.</p></section>
        <section id="testing"><div className="eyebrow">07 / ACTIVATION & VERIFICATION</div><h2>Real receipts.<br />A proven cycle.</h2><p>Illustrative examples explain the rules. They create no token and send no funds. <strong>They are not proof of live payouts.</strong></p><p>A real controlled acceptance test must demonstrate: launch → verified buy → attributable funding → finalized eligibility → funded allocation → confirmed payout → public proof → restart without duplication. A price drop and actual eligible loss are required; do not manipulate a market to manufacture eligibility.</p><p>Operators must configure public reward and protocol treasury addresses, verify database and worker health, and explicitly enable controlled launches. No seed phrase or private key should be pasted into chat, Vercel, or Railway for manual-wallet mode.</p><aside className="docs-callout"><strong>DRY_RUN is not a free-launch switch.</strong><p>With launches enabled, creation is a real mainnet transaction even when DRY_RUN is true. Dry run locks funding and payout submission. Turning it off and enabling epoch planning should follow review of the controlled real-funds test.</p></aside><div className="hero-actions"><Link href="/launch" className="button">Launch token</Link><Link href="/explore" className="button button-secondary">Explore launches</Link></div></section>
        <section id="not"><h2>What this is not.</h2><p>TopBlast is not an exchange, bonding curve, AMM, insurance policy, or guaranteed loss-recovery product. Venue names identify integrations, not endorsement or operation by those venues.</p></section>
        <section id="weighted-entry"><h2>Your weighted entry.</h2><p>Only verified market buys establish cost. Buy 10 units for 20 quote units, then 10 for 40: the retained 20-unit position has an average entry of 3 quote units. Received tokens establish no new purchased basis. Outgoing activity consumes verified units first and excludes the wallet for the applicable epoch.</p><p>Calculations use actual mint decimals and integer base units. UI spot prices are not authorization for a payout; the finalized snapshot uses its validated price source.</p></section>
        <section id="epochs"><h2>One finalized checkpoint.</h2><p>Schedule → acquire worker lease → reconcile finalized history → validate snapshot price → reserve attributable funding → record wallet snapshots → calculate loss-weighted allocations → prepare batches → obtain treasury approval → submit → reconcile finality → publish proof.</p><p>Missing history, stale price, unsupported markets and engine pauses stop payable allocation. A zero-funded epoch cannot distribute rewards.</p></section>
        <section id="allocation"><h2>Fixed at launch.</h2><p>The fixed 10% protocol share and the creator’s division of the remaining 90% apply to explicit funding, not trades. The final gross allocation must total 100%. New launch controls use exact whole-percent policies, subject to the configured minimum reward allocation. The review shows both percentages before approval.</p></section>
        <section id="payout-approval"><h2>Your treasury pays holders.</h2><p>TopBlast prepares launch-scoped direct-airdrop batches containing the exact asset, recipients, amounts, fee payer and network. Manual mode uses treasury-wallet approval. Server mode uses a Railway-only key that must match the configured treasury, signs only the stored message, enforces a per-batch ceiling and serializes unresolved spending.</p><p>Holders never claim. Never approve an unexplained transfer. Reserved and submitted balances are not confirmed payouts.</p></section>
        <section id="recovery"><h2>Recover the receipt.<br />Do not pay twice.</h2><p>After a timeout, refresh or closed tab, use the saved launch or funding receipt. A delayed response does not establish failure. The server binds signed transactions before broadcasting and reconciles their finality. A restart must resume the same payment, not generate a replacement.</p><p>Partial payout recovery operates per batch and recipient. Confirmed transfers stay paid; unresolved batches remain reserved or submitted until reconciled. Retry tracking after a completed launch without creating another token.</p></section>
        <section id="limitations"><h2>Know the boundaries.</h2><ul><li>Automatic venue-fee funding is not deployed. Creators explicitly deposit.</li><li>Pump is beta: official creation only, no initial buy, native cashback, mayhem or non-SOL pairs.</li><li>PumpSwap graduation is unsupported. Tracking and new epochs pause after unsupported graduation.</li><li>Unproven production acceptance means public launches stay disabled. A passing build is not a payout receipt.</li><li>Controlled tests are real mainnet tokens and may be visibly labelled as tests. Hiding a listing cannot remove onchain history.</li></ul></section>
        <section id="security"><h2>Exact transactions only.</h2><p>Never paste private keys or recovery phrases into this site, chat, browser storage, Supabase, Vercel or Git. Connect only through a trusted wallet and review each exact transaction. If automatic payouts are selected, the treasury key is entered directly into Railway’s protected worker variables and nowhere else.</p><p>Financial records are scoped to launch IDs. Funding signatures cannot be reused across launches; database reservations prevent competing epochs from spending the same budget. Public readers cannot modify financial records. Operator actions require separate authorization; connecting a wallet to view public data does not grant administrative access.</p><p>Report unexpected recipients, missing receipts or inconsistent balances before signing anything else. Large treasury movements should use an independently reviewed approval process.</p></section>
        <section id="risks"><h2>Participation.<br />Not protection.</h2><p>TopBlast rewards participation. It does not promise to recover losses. Token prices can fall to zero. Eligibility and funding may be insufficient, delayed or unavailable. Venue, RPC, wallet and smart-contract failures can interrupt operation. No APY, guaranteed payment or guaranteed principal recovery is offered.</p></section>
      </article>
    </div>
  </main>;
}
