"use client";
import { useState } from "react";

export function AdminPanel(){
  const [token,setToken]=useState("");const [status,setStatus]=useState<Record<string,unknown>|null>(null);const [message,setMessage]=useState("");const [launchId,setLaunchId]=useState("");const [epochId,setEpochId]=useState("");
  async function load(){const response=await fetch("/api/admin/action",{headers:{Authorization:`Bearer ${token}`}});const body=await response.json();if(!response.ok){setMessage(body.error);return}setStatus(body);setMessage("")}
  async function action(name:string){const response=await fetch("/api/admin/action",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({action:name,launchId,epochId})});const body=await response.json();setMessage(response.ok?JSON.stringify(body):body.error);if(response.ok)await load()}
  const metric=(label:string,key:string)=><div className="metric"><span>{label}</span><strong>{String(status?.[key]??"-")}</strong></div>;
  return <><div className="panel"><div className="field"><label>Admin token</label><input type="password" value={token} onChange={(event)=>setToken(event.target.value)} /><button className="button" type="button" onClick={load}>Load health</button></div></div>{status&&<div className="stats-grid">{metric("Active launches","activeLaunches")}{metric("Tracker health","trackerHealth")}{metric("Last indexed block","lastIndexedBlock")}{metric("Failed epochs","failedEpochs")}{metric("Failed payouts","failedPayouts")}{metric("Unclaimed fees","unclaimedFeesAtoms")}{metric("Treasury balances","treasuryBalances")}</div>}<div className="panel" style={{marginTop:24}}><div className="section-label">Controls</div><div className="form-grid" style={{marginTop:16}}><div className="field"><label>Launch ID</label><input value={launchId} onChange={(event)=>setLaunchId(event.target.value)} /><button className="button button-secondary" type="button" onClick={()=>action("pause_launch")}>Pause specific launch</button></div><div className="field"><label>Epoch ID</label><input value={epochId} onChange={(event)=>setEpochId(event.target.value)} /><button className="button button-secondary" type="button" onClick={()=>action("retry_epoch")}>Retry failed epoch</button><button className="button button-secondary" type="button" onClick={()=>action("dry_run_payout")}>Dry run payout</button></div></div><button className="button" style={{marginTop:20}} type="button" onClick={()=>action("pause_engine")}>Pause reward engine</button>{message&&<div className="notice" style={{marginTop:16}}>{message}</div>}</div></>;
}
