"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

const display = (value: unknown, fallback = "Pending") => value === null || value === undefined ? fallback : String(value);
const money = (value: unknown) => typeof value === "number" ? new Intl.NumberFormat("en", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 2 }).format(value) : "Pending";

export function TokenPage({ address }: { address: string }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null);
  const [error, setError] = useState("");
  const [wallet, setWallet] = useState("");
  const [holder, setHolder] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { fetch(`/api/token/${address}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch((caught) => setError(caught.message)); }, [address]);
  async function lookup() { const response = await fetch(`/api/token/${address}/wallet/${encodeURIComponent(wallet)}`); const body = await response.json(); if (!response.ok) { setError(body.error); return; } setHolder(body); }
  if (error && !data) return <main className="page shell"><div className="error">{error}</div></main>;
  if (!data) return <main className="page shell"><div className="empty">Loading verified launch data...</div></main>;
  const launch = data.launch as Record<string, unknown>;
  const config = Array.isArray(launch.launch_configs) ? launch.launch_configs[0] : launch.launch_configs as Record<string, unknown> | undefined;
  const epochs = data.epochs as Record<string, unknown>[];
  return <main><section className="token-hero"><div className="shell"><span className="status-pill">TOPBLAST ENABLED</span><h1>{String(launch.name)}<span>${String(launch.symbol)} · {String(launch.symbol)} / {String(launch.quote_symbol)}</span></h1><p className="mono">{address}</p></div></section><div className="shell page"><div className="stats-grid"><div className="metric"><span>Price</span><strong>{money(launch.price_usd)}</strong></div><div className="metric"><span>Market cap</span><strong>{money(launch.market_cap_usd)}</strong></div><div className="metric"><span>24h volume</span><strong>{money(launch.volume_24h_usd)}</strong></div><div className="metric"><span>Liquidity</span><strong>{money(launch.liquidity_usd)}</strong></div></div><div className="stats-grid"><div className="metric"><span>Reward pool</span><strong>Funded only</strong></div><div className="metric"><span>Eligible wallets</span><strong>{display((epochs[0] as Record<string, unknown> | undefined)?.eligible_wallets, "0")}</strong></div><div className="metric"><span>Total rewarded</span><strong>{display(data.totalRewardedAtoms, "0")} atoms</strong></div><div className="metric"><span>Next epoch</span><strong>{epochs[0] ? "Scheduled" : "Awaiting fees"}</strong></div></div><section className="how"><div><div className="eyebrow">BLAST ZONE</div><h2>YOUR ENTRY<br />SETS THE LINE.</h2><p className="notice">Reward allocation: {display(config?.topblast_percent)}% TopBlast, {display(config?.creator_percent)}% creator, {display(config?.protocol_percent)}% protocol.</p></div><div className="blast-diagram"><div><span>YOUR VERIFIED ENTRY</span><b /></div><p>Current price below</p><div className="blast-zone">BLAST ZONE</div><small>Below your verified entry. Still holding. Eligible for funded TopBlast rewards.</small></div></section><section className="panel"><div className="section-label">Holder lookup</div><h3>Check a wallet</h3><div className="lookup"><input value={wallet} onChange={(event) => setWallet(event.target.value)} placeholder="Wallet address" /><button className="button" onClick={lookup}>Check</button></div>{holder && <div className="stats-grid"><div className="metric"><span>Average entry</span><strong>{display(holder.averageEntry)}</strong></div><div className="metric"><span>Current value</span><strong>{display(holder.currentValue)}</strong></div><div className="metric"><span>Draw down</span><strong>{display(holder.drawdown)}</strong></div><div className="metric"><span>Status</span><strong>{display(holder.status)}</strong></div><div className="metric"><span>Eligible units</span><strong>{display(holder.eligibleUnits)}</strong></div><div className="metric"><span>Rewards received</span><strong>{display(holder.rewardsReceived)}</strong></div></div>}</section><p style={{marginTop:24}}><Link className="button button-secondary" href={`/token/${address}/proof`}>View epoch proof</Link></p></div></main>;
}
