import { test, expect } from "@playwright/test";

test("docs explain real funding, Pump limits, and safe testing on every viewport", async ({ page }) => {
  const writes: string[] = [];
  page.on("request", (request) => { if (!["GET", "HEAD"].includes(request.method())) writes.push(request.url()); });
  await page.goto("/docs");
  await expect(page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Docs", exact: true })).toBeVisible();
  await expect(page.getByText("Automatic creator-fee routing is not active.", { exact: false })).toBeVisible();
  await expect(page.getByText("PumpSwap graduation is not supported.", { exact: false })).toBeVisible();
  await expect(page.getByRole("row").filter({ hasText: "Pump.fun" })).toContainText("Wrapped SOL (WSOL)");
  await page.getByRole("navigation", { name: "Documentation sections" }).getByRole("link", { name: "Read the proof" }).click();
  await expect(page).toHaveURL(/#proof$/);
  await expect(page.getByRole("heading", { name: "Allocated does not mean paid." })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
  await page.getByRole("link", { name: "Run free simulation", exact: true }).click();
  await expect(page.getByText("SIMULATION ONLY · NOT DEVNET")).toBeVisible();
  expect(writes).toEqual([]);
});

test("interactive docs teach eligibility without signing or submitting funds", async ({ page }) => {
  const writes: string[] = [];
  const errors: string[] = [];
  page.on("request", (request) => { if (!["GET", "HEAD"].includes(request.method())) writes.push(request.url()); });
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/docs");
  await page.getByRole("button", { name: "I’m holding", exact: true }).click();
  const holdingStep = page.getByRole("button", { name: "02 Keep holding", exact: true });
  await holdingStep.focus();
  await holdingStep.press("Enter");
  await expect(page.getByRole("heading", { name: "Below entry. Still in position." })).toBeVisible();
  await expect(page.getByText("There is no private-key upload step.", { exact: false })).toBeVisible();
  const lab = page.getByRole("region", { name: "Illustrative eligibility lab" });
  const result = lab.getByRole("status");
  await expect(result).toContainText("ELIGIBLE · FUNDED EXAMPLE");
  await expect(result).toContainText("56.00");
  await lab.getByRole("button", { name: "Receive 5 tokens", exact: true }).click();
  await expect(result).toContainText("20 verified units, not 25");
  await expect(result).toContainText("56.00");
  await lab.getByRole("button", { name: "Sell 5 tokens", exact: true }).click();
  await expect(result).toContainText("SOLD THIS EPOCH");
  await expect(result).toContainText("0.00");
  await lab.getByRole("button", { name: "Send 5 tokens", exact: true }).click();
  await expect(result).toContainText("TRANSFERRED");
  await lab.getByRole("button", { name: "Never bought", exact: true }).click();
  await expect(result).toContainText("NOT A VERIFIED BUYER");
  await expect(result).toContainText("0.00");
  await lab.getByRole("button", { name: "Still holding", exact: true }).click();
  await lab.getByRole("checkbox").uncheck();
  await expect(result).toContainText("ELIGIBLE · NO FUNDING");
  await expect(result).toContainText("0.00");
  const price = lab.getByRole("slider", { name: "Sample price", exact: false });
  await price.focus();
  await price.press("End");
  await expect(result).toContainText("ABOVE ENTRY");
  await lab.getByRole("button", { name: "Reset the example" }).click();
  await expect(result).toContainText("56.00");
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
  expect(writes).toEqual([]);
  expect(errors).toEqual([]);
});
